name: Automatic version control

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true
          
      - name: Git Semantic Versión
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "major:"
          minor_pattern: "minor:"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version